#!/usr/bin/env python3
"""Generate docs/matchups.js from matchups/*.md
Usage: python scripts/generate_matchups_js.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MATCHUPS_DIR = ROOT / "matchups"
OUTPUT = ROOT / "docs" / "matchups.js"

CHARACTER_ALIASES: dict[str, str] = {
    "LUKE": "LUKE", "Luke": "LUKE", "ルーク": "LUKE",
    "JAMIE": "JAMIE", "Jamie": "JAMIE", "ジェイミー": "JAMIE",
    "MANON": "MANON", "Manon": "MANON", "マノン": "MANON",
    "KIMBERLY": "KIMBERLY", "Kimberly": "KIMBERLY", "キンバリー": "KIMBERLY",
    "MARISA": "MARISA", "Marisa": "MARISA", "マリーザ": "MARISA",
    "LILY": "LILY", "Lily": "LILY", "リリー": "LILY",
    "JP": "JP",
    "JURI": "JURI", "Juri": "JURI", "ジュリ": "JURI",
    "DEE JAY": "DEE JAY", "Dee Jay": "DEE JAY", "ディージェイ": "DEE JAY",
    "CAMMY": "CAMMY", "Cammy": "CAMMY", "キャミィ": "CAMMY",
    "RYU": "RYU", "Ryu": "RYU", "リュウ": "RYU",
    "E. HONDA": "E. HONDA", "E. Honda": "E. HONDA", "エドモンド本田": "E. HONDA",
    "BLANKA": "BLANKA", "Blanka": "BLANKA", "ブランカ": "BLANKA",
    "GUILE": "GUILE", "Guile": "GUILE", "ガイル": "GUILE",
    "KEN": "KEN", "Ken": "KEN", "ケン": "KEN",
    "CHUN-LI": "CHUN-LI", "Chun-Li": "CHUN-LI", "春麗": "CHUN-LI",
    "ZANGIEF": "ZANGIEF", "Zangief": "ZANGIEF", "ザンギエフ": "ZANGIEF",
    "DHALSIM": "DHALSIM", "Dhalsim": "DHALSIM", "ダルシム": "DHALSIM",
    "RASHID": "RASHID", "Rashid": "RASHID", "ラシード": "RASHID",
    "A.K.I.": "A.K.I.", "A.K.I": "A.K.I.", "AKI": "A.K.I.", "アキ": "A.K.I.",
    "ED": "ED", "Ed": "ED", "エド": "ED",
    "AKUMA": "AKUMA", "Gouki": "AKUMA", "豪鬼": "AKUMA",
    "M. BISON": "M. BISON", "M. Bison": "M. BISON", "ベガ": "M. BISON",
    "TERRY": "TERRY", "Terry": "TERRY", "テリー": "TERRY",
    "MAI": "MAI", "Mai": "MAI", "不知火舞": "MAI",
    "ELENA": "ELENA", "Elena": "ELENA", "エレナ": "ELENA",
    "SAGAT": "SAGAT", "Sagat": "SAGAT", "サガット": "SAGAT",
    "C. VIPER": "C. VIPER", "C. Viper": "C. VIPER", "クリムゾン・ヴァイパー": "C. VIPER",
}


def parse_matchup(file: Path) -> list[str]:
    entries = []
    for raw_line in file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        line = line.replace("**", "")
        line = re.sub(r"\s+", " ", line)
        entries.append(line)
    return entries


data: dict[str, list[str]] = {}
for file in sorted(MATCHUPS_DIR.glob("*.md")):
    name = file.stem
    entries = parse_matchup(file)
    if entries:
        data[name] = entries

OUTPUT.parent.mkdir(exist_ok=True)
OUTPUT.write_text(
    "// Auto-generated by scripts/generate_matchups_js.py — do not edit manually\n\n"
    f"const MATCHUP_DATA = {json.dumps(data, ensure_ascii=False, indent=2)};\n\n"
    f"const CHARACTER_ALIASES = {json.dumps(CHARACTER_ALIASES, ensure_ascii=False, indent=2)};\n\n"
    "const CHARACTER_LIST = [...new Set(Object.values(CHARACTER_ALIASES))];\n",
    encoding="utf-8",
)
print(f"Generated {OUTPUT} — {len(data)} characters")
